GradeBook/config/routes.rb
Rails.application.routes.draw do

  # main resources
  # --------------------------------------------------------

  # Home pages
  authenticated :user do
    root to: 'users/home#index', as: :authenticated_root
  end
  root "home#index"

  # Authenticated pages
  resources :grades
  resources :dispensed_lectures
  resources :promotions
  resources :dispensed_lecture
  resources :user_promotions
  resources :lectures
  resources :lectures

  # devise routes
  # --------------------------------------------------------
  get '/login', to: 'users/sessions#new'
  post '/login', to: 'users/sessions#create'
  get '/change_password', to: 'users/passwords#edit'
  patch '/change_password', to: 'users/passwords#update'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end


end

GradeBook/app/models/promotion.rb
class Promotion < ApplicationRecord
  has_many :user_promotions
  has_many :users, through: :user_promotions
  has_many :dispensed_lectures
  has_many :lectures, through: :dispensed_lectures

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

GradeBook/app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_promotion, only: %i[ show edit update destroy ]
  before_action :require_teacher, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  # GET /promotions or /promotions.json
  def index
    @promotions = Promotion.all
  end

  # GET /promotions/1 or /promotions/1.json
  def show
    @promotion = Promotion.find(params[:id])
  end

  # GET /promotions/new
  def new
    @promotion = Promotion.new
  end

  # GET /promotions/1/edit
  def edit
  end

  # POST /promotions or /promotions.json
  def create
    @promotion = Promotion.new(promotion_params)

    respond_to do |format|
      if @promotion.save
        format.html { redirect_to promotion_url(@promotion), notice: "Promotion was successfully created." }
        format.json { render :show, status: :created, location: @promotion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promotions/1 or /promotions/1.json
  def update
    respond_to do |format|
      if @promotion.update(promotion_params)
        format.html { redirect_to promotion_url(@promotion), notice: "Promotion was successfully updated." }
        format.json { render :show, status: :ok, location: @promotion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1 or /promotions/1.json
  def destroy
    @promotion.destroy

    respond_to do |format|
      format.html { redirect_to promotions_url, notice: "Promotion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_promotion
    @promotion = Promotion.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def promotion_params
    params.require(:promotion).permit(:name, :start_date, :end_date, :user_id)
  end

  def require_teacher
    if not current_user.teacher?
      redirect_to root_path, alert: "You're not allowed to access to this content."
    end
  end
end

GradeBook/app/helpers/promotions_helper.rb
module PromotionsHelper
end

GradeBook/app/views/promotions/_form.html.erb
<%= form_with(model: promotion, class: "contents") do |form| %>
  <% if promotion.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

      <ul>
        <% promotion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :end_date %>
    <%= form.date_field :end_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.select :user_id, options_for_select(User.where(user_type_id: UserType.find_by(slug: 'TEA')).map { |p| [p.full_name, p.id] }), class: "form-select" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

GradeBook/app/views/promotions/_promotion.html.erb
<div id="<%= dom_id promotion %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= promotion.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Start date:</strong>
    <%= promotion.start_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">End date:</strong>
    <%= promotion.end_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Teacher:</strong>
    <% teacher = User.find(promotion.user_id) %>
    <%= teacher.full_name %>
  </p>

  <p class="mb-4">
    <strong class="block font-medium mb-0">Students:</strong>
  <ul class="mt-0">
    <% if promotion.present? && promotion.users.present? %>
      <% promotion.users.each do |student| %>
        <li><%= student.full_name %></li>
      <% end %>
    <% else %>
      <li>No students found.</li>
    <% end %>
  </ul>
  </p>
  <br>


  <% if action_name != "show" %>
    <%= link_to "Show this promotion", promotion, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this promotion', edit_promotion_path(promotion), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

GradeBook/app/views/promotions/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing promotion</h1>

  <%= render "form", promotion: @promotion %>

  <%= link_to "Show this promotion", @promotion, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to promotions", promotions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

GradeBook/app/views/promotions/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Promotions</h1>
  </div>
  <% if current_user.teacher? %>
    <div class="bg-orange-100 border-l-4 border-orange-500 text-orange-700 p-4" role="alert">
      <p class="font-bold">Create a lecture</p>
      <ul>
        <li>1. Create a promotion</li>
        <li>2. Assign students to a promotion</li>
      </ul>
    </div>
  <% end %>
  <div class="flex justify-between items-center">
    <%= link_to 'New promotion', new_promotion_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <%= link_to 'Add student to a promotion', new_user_promotion_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="promotions" class="min-w-full">
    <%= render @promotions %>
  </div>

</div>

GradeBook/app/views/promotions/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New promotion</h1>

  <%= render "form", promotion: @promotion %>

  <%= link_to 'Back to promotions', promotions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

GradeBook/app/views/promotions/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @promotion %>

    <div class="inline-block ml-2">
      <%= link_to 'Add student to a promotion', new_user_promotion_path, class: "rounded-lg py-3 px-5 bg-gray-800 text-white block font-medium" %>
    </div>

    <div class="inline-block ml-2">
      <%= link_to 'Edit this promotion', edit_promotion_path(@promotion), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this promotion', promotion_path(@promotion), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <div class="inline-block ml-2">
      <%= link_to 'Back to promotions', promotions_path, class: " rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
  </div>
</div>