GradeBook/config/routes.rb
Rails.application.routes.draw do

  # main resources
  # --------------------------------------------------------

  # Home pages
  authenticated :user do
    root to: 'users/home#index', as: :authenticated_root
  end
  root "home#index"

  # Authenticated pages
  resources :grades
  resources :dispensed_lectures
  resources :promotions
  resources :dispensed_lecture
  resources :user_promotions
  resources :lectures
  resources :lectures

  # devise routes
  # --------------------------------------------------------
  get '/login', to: 'users/sessions#new'
  post '/login', to: 'users/sessions#create'
  get '/change_password', to: 'users/passwords#edit'
  patch '/change_password', to: 'users/passwords#update'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end


end

GradeBook/app/views/layouts/_lateral_navbar.html.erb
<nav aria-label="alternative nav bg-gray-800">
  <div class="bg-gray-800 shadow-xl h-20 fixed bottom-0 mt-12 md:relative md:h-screen z-10 w-full md:w-48 content-center">

    <div class="md:mt-12 md:w-48 md:fixed md:left-0 md:top-0 content-center md:content-start text-left justify-between bg-gray-800">
      <ul class="list-reset flex flex-row md:flex-col pt-3 md:py-3 px-1 md:px-2 text-center md:text-left">
        <% if current_user.teacher? %>
          <li class="mr-3 flex-1">
            <%= link_to 'Home', authenticated_root_path, class: "block py-1 md:py-3 pl-0 md:pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-red-500" %>
          </li>
          <li class="mr-3 flex-1">
            <%= link_to 'Promotions', promotions_path, class: "block py-1 md:py-3 pl-0 md:pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-red-500" %>
          </li>
          <li class="mr-3 flex-1">
            <%= link_to 'Lectures', lectures_path, class: "block py-1 md:py-3 pl-0 md:pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-red-500" %>
          </li>
        <% end %>
        <% if current_user.teacher? || current_user.student? %>
          <li class="mr-3 flex-1">
            <%= link_to 'Grades', grades_path, class: "block py-1 md:py-3 pl-0 md:pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-red-500" %>
          </li>
        <% end %>
      </ul>
    </div>


  </div>
</nav>

GradeBook/app/views/layouts/_navbar.html.erb
<!--Nav-->
<nav aria-label="menu nav" class="bg-gray-800 pt-2 md:pt-1 pb-1 px-1 mt-0 h-auto fixed w-full z-20 top-0">

  <div class="flex flex-wrap items-center">
    <div class="flex flex-shrink md:w-1/3 justify-center md:justify-start text-white">
      <a href="#" aria-label="Home">
        <span class="text-xl pl-2"><i class="em em-grinning"></i></span>
      </a>
    </div>
    <div class="flex flex-1 md:w-1/3 justify-center md:justify-start text-white px-2">
    </div>

    <div class="flex w-full pt-2 content-center justify-between md:w-1/3 md:justify-end">
      <ul class="list-reset flex justify-between flex-1 md:flex-none items-center">

        <li class="flex-1 md:flex-none md:mr-3">
          <div class="relative inline-block">
            <button onclick="toggleDD('myDropdown')" class="drop-button text-white py-2 px-2">
              <span class="pr-2"><i class="em em-robot_face"></i></span> <%= current_user.lastname %>
              , <%= current_user.firstname %> (<%= current_user.user_type.name %>)
              <svg class="h-3 fill-current inline" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/>
              </svg>
            </button>
            <div id="myDropdown" class="dropdownlist absolute bg-gray-800 text-white right-0 mt-3 p-3 overflow-auto z-30 invisible">
              <div class="border border-gray-800">
                <%= link_to "Edit Profile", edit_user_registration_path %>
              </div>
              <div class="border border-gray-800">
                <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

GradeBook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GradeBook</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= hotwire_livereload_tags if Rails.env.development? %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
  <%= csrf_meta_tags %>
</head>

<body class="bg-gray-800 font-sans leading-normal tracking-normal mt-12">
<% if user_signed_in? %>
  <header>
    <%= render 'layouts/navbar' %>
  </header>
  <main>
    <div class="flex flex-col md:flex-row bg-white">
      <% if user_signed_in? %>
        <%= render 'layouts/lateral_navbar' %>
      <% end %>
      <section class="bg-white">
        <div id="main" class="main-content flex-1 mt-12 md:mt-2 pb-24 md:pb-5 bg-white">
          <div class="w-full flex flex-wrap">
            <div class="w-full md:w-2/2 xl:w-3/3 p-6">
              <p class="alert"><%= alert %></p>
              <%= yield %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </main>
<% else %>
  <main class="container mx-auto mt-10 px-5 flex">
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </main>
<% end %>
<% if user_signed_in? %>
  <script>
      /*Toggle dropdown list*/
      function toggleDD(myDropMenu) {
          document.getElementById(myDropMenu).classList.toggle("invisible");
      }

      /*Filter dropdown options*/
      function filterDD(myDropMenu, myDropMenuSearch) {
          var input, filter, ul, li, a, i;
          input = document.getElementById(myDropMenuSearch);
          filter = input.value.toUpperCase();
          div = document.getElementById(myDropMenu);
          a = div.getElementsByTagName("a");
          for (i = 0; i < a.length; i++) {
              if (a[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
                  a[i].style.display = "";
              } else {
                  a[i].style.display = "none";
              }
          }
      }

      // Close the dropdown menu if the user clicks outside of it
      window.onclick = function (event) {
          if (!event.target.matches('.drop-button') && !event.target.matches('.drop-search')) {
              var dropdowns = document.getElementsByClassName("dropdownlist");
              for (var i = 0; i < dropdowns.length; i++) {
                  var openDropdown = dropdowns[i];
                  if (!openDropdown.classList.contains('invisible')) {
                      openDropdown.classList.add('invisible');
                  }
              }
          }
      }
  </script>
<% end %>
</body>
</html>