GradeBook/config/routes.rb
Rails.application.routes.draw do

  # main resources
  # --------------------------------------------------------

  # Home pages
  authenticated :user do
    root to: 'users/home#index', as: :authenticated_root
  end
  root "home#index"

  # Authenticated pages
  resources :grades
  resources :dispensed_lectures
  resources :promotions
  resources :dispensed_lecture
  resources :user_promotions
  resources :lectures
  resources :lectures

  # devise routes
  # --------------------------------------------------------
  get '/login', to: 'users/sessions#new'
  post '/login', to: 'users/sessions#create'
  get '/change_password', to: 'users/passwords#edit'
  patch '/change_password', to: 'users/passwords#update'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end


end

GradeBook/app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :category, class_name: 'Category'
  has_many :dispensed_lectures
  has_many :promotions, through: :dispensed_lectures
  has_many :grades, through: :dispensed_lectures


  validates :name, presence: true
  validates :description, presence: true

  delegate :name, to: :category, prefix: true, allow_nil: true
end

GradeBook/app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lecture, only: %i[ show edit update destroy ]
  before_action :require_teacher, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  # GET /lectures or /lectures.json
  def index
    @lectures = current_user.lectures
  end

  # GET /lectures/1 or /lectures/1.json
  def show
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures or /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to lecture_url(@lecture), notice: "Lecture was successfully created." }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1 or /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to lecture_url(@lecture), notice: "Lecture was successfully updated." }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1 or /lectures/1.json
  def destroy
    @lecture.destroy

    respond_to do |format|
      format.html { redirect_to lectures_url, notice: "Lecture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lecture
    @lecture = Lecture.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lecture_params
    params.require(:lecture).permit(:name, :description, :category_id)
  end

  def require_teacher
    if not current_user.teacher?
      redirect_to root_path, alert: "You're not allowed to access to this content."
    end
  end
end

GradeBook/app/helpers/lectures_helper.rb
module LecturesHelper
end

GradeBook/app/views/lectures/_form.html.erb
<%= form_with(model: lecture, class: "contents") do |form| %>
  <% if lecture.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
        <% lecture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category_id, style: "display: block" %>
    <%= form.select :category_id, options_for_select(Category.all.map { |c| [c.name, c.id] }), {}, class: "form-control", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

GradeBook/app/views/lectures/_lecture.html.erb
<div id="<%= dom_id lecture %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= lecture.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= lecture.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= lecture.category_name %>
  </p>

  <p class="mb-4">
    <strong class="block font-medium mb-0">Dispensed to:</strong>
  <ul class="mt-0">
    <% if lecture.present? && lecture.promotions.present? %>
      <% lecture.promotions.each do |promotion| %>
        <li> <%= "#{promotion.name} (#{promotion.start_date.strftime('%Y')}-#{promotion.end_date.strftime('%Y')})" %></li>
      <% end %>
    <% else %>
      <li>No promotion found.</li>
    <% end %>
  </ul>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Give a grade", new_grade_path, class: "rounded-lg py-3 px-5 bg-gray-800 text-white inline-block font-medium" %>
    <%= link_to "Show this lecture", lecture, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this lecture', edit_lecture_path(lecture), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

GradeBook/app/views/lectures/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing lecture</h1>

  <%= render "form", lecture: @lecture %>

  <%= link_to "Show this lecture", @lecture, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to lectures", lectures_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

GradeBook/app/views/lectures/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex justify-between items-center mt-2">
    <h1 class="font-bold text-4xl">Lectures</h1>
  </div>
  <% if current_user.teacher? %>
    <div class="bg-orange-100 border-l-4 border-orange-500 text-orange-700 p-4" role="alert">
      <p class="font-bold">Create a lecture</p>
      <ul>
        <li>1. Create a lecture</li>
        <li>2. Assign promotion to a lecture</li>
      </ul>
    </div>
  <% end %>
  <div class="flex space-between items-center mt-2">
    <%= link_to 'New lecture', new_lecture_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <%= link_to "Assign a promotion to a lecture", new_dispensed_lecture_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <br>
  </div>

  <div id="lectures" class="min-w-full">
    <div id="lectures" class="min-w-full">
      <% if @lectures.present? %>
        <%= render @lectures %>
      <% else %>
        <p>No lectures found.</p>
      <% end %>
    </div>
  </div>
</div>

GradeBook/app/views/lectures/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New lecture</h1>

  <%= render "form", lecture: @lecture %>

  <%= link_to 'Back to lectures', lectures_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

GradeBook/app/views/lectures/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @lecture %>
    <%= link_to "Create a new grade", new_grade_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this lecture', edit_lecture_path(@lecture), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this lecture', lecture_path(@lecture), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to lectures', lectures_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>