GradeBook/config/routes.rb
Rails.application.routes.draw do

  # main resources
  # --------------------------------------------------------

  # Home pages
  authenticated :user do
    root to: 'users/home#index', as: :authenticated_root
  end
  root "home#index"

  # Authenticated pages
  resources :grades
  resources :dispensed_lectures
  resources :promotions
  resources :dispensed_lecture
  resources :user_promotions
  resources :lectures
  resources :lectures

  # devise routes
  # --------------------------------------------------------
  get '/login', to: 'users/sessions#new'
  post '/login', to: 'users/sessions#create'
  get '/change_password', to: 'users/passwords#edit'
  patch '/change_password', to: 'users/passwords#update'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end


end

GradeBook/app/models/dispensed_lecture.rb
class DispensedLecture < ApplicationRecord
  belongs_to :lecture
  belongs_to :promotion
  belongs_to :user
  belongs_to :semester
  has_many :grades

  delegate :name, to: :lecture, prefix: true

  validates :lecture, presence: true
  validates :promotion, presence: true
  validates :user, presence: true
  validates :semester, presence: true
end

GradeBook/app/controllers/dispensed_lectures_controller.rb
class DispensedLecturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_dispensed_lecture, only: %i[ show edit update destroy ]
  before_action :require_teacher, only: [:index, :show, :new, :edit, :create, :update, :destroy]


  # GET /dispensed_lectures or /dispensed_lectures.json
  def index
    redirect_to '/lectures'
  end

  # GET /dispensed_lectures/1 or /dispensed_lectures/1.json
  def show
    redirect_to '/lectures'
  end

  # GET /dispensed_lectures/new
  def new
    @dispensed_lecture = DispensedLecture.new
  end

  # GET /dispensed_lectures/1/edit
  def edit
    @dispensed_lecture = DispensedLecture.find(params[:id])
  end

  # POST /dispensed_lectures or /dispensed_lectures.json
  def create
    @dispensed_lecture = DispensedLecture.new(dispensed_lecture_params)

    respond_to do |format|
      if @dispensed_lecture.save
        format.html { redirect_to dispensed_lecture_url(@dispensed_lecture), notice: "Dispensed lecture was successfully created." }
        format.json { render :show, status: :created, location: @dispensed_lecture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dispensed_lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dispensed_lectures/1 or /dispensed_lectures/1.json
  def update
    respond_to do |format|
      if @dispensed_lecture.update(dispensed_lecture_params)
        format.html { redirect_to dispensed_lecture_url(@dispensed_lecture), notice: "Dispensed lecture was successfully updated." }
        format.json { render :show, status: :ok, location: @dispensed_lecture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dispensed_lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dispensed_lectures/1 or /dispensed_lectures/1.json
  def destroy
    @dispensed_lecture.destroy

    respond_to do |format|
      format.html { redirect_to dispensed_lectures_url, notice: "Dispensed lecture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dispensed_lecture
      @dispensed_lecture = DispensedLecture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dispensed_lecture_params
      params.require(:dispensed_lecture).permit(:lecture_id, :promotion_id, :semester_id, :user_id)
    end

  def require_teacher
    if not current_user.teacher?
      redirect_to root_path, alert: "You're not allowed to access to this content."
    end
  end

end

GradeBook/app/helpers/dispensed_lectures_helper.rb
module DispensedLecturesHelper
end

GradeBook/app/views/dispensed_lectures/_dispensed_lecture.html.erb
<div id="<%= dom_id dispensed_lecture %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Lecture:</strong>
    <%= dispensed_lecture.lecture_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Promotion:</strong>
    <%= dispensed_lecture.promotion_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Semester:</strong>
    <%= dispensed_lecture.semester_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= dispensed_lecture.user_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this dispensed lecture", dispensed_lecture, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this dispensed lecture', edit_dispensed_lecture_path(dispensed_lecture), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

GradeBook/app/views/dispensed_lectures/_form.html.erb
<%= form_with(model: dispensed_lecture, class: "contents") do |form| %>
  <% if dispensed_lecture.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(dispensed_lecture.errors.count, "error") %> prohibited this dispensed_lecture from being saved:</h2>

      <ul>
        <% dispensed_lecture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :lecture_id %>
    <%= form.select :lecture_id, options_for_select(Lecture.all.map { |p| [p.name, p.id] }), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :promotion_id %>
    <%= form.select :promotion_id, options_for_select(Promotion.all.map { |p| [p.name, p.id] }), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :semester_id %>
    <%= form.select :semester_id, options_for_select(Semester.all.map { |p| [p.name, p.id] }), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.select :user_id, options_for_select(User.where(user_type_id: UserType.find_by(slug: 'TEA')).map { |p| [p.full_name, p.id] }), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

GradeBook/app/views/dispensed_lectures/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing dispensed lecture</h1>

  <%= render "form", dispensed_lecture: @dispensed_lecture %>

  <%= link_to "Show this dispensed lecture", @dispensed_lecture, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to dispensed lectures", dispensed_lectures_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

GradeBook/app/views/dispensed_lectures/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Dispensed lectures</h1>
    <%= link_to 'New dispensed lecture', new_dispensed_lecture_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="dispensed_lectures" class="min-w-full">
    <%= render @dispensed_lectures %>
  </div>
</div>

GradeBook/app/views/dispensed_lectures/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New dispensed lecture</h1>

  <%= render "form", dispensed_lecture: @dispensed_lecture %>

  <%= link_to 'Back to dispensed lectures', dispensed_lectures_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

GradeBook/app/views/dispensed_lectures/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @dispensed_lecture %>

    <%= link_to 'Edit this dispensed_lecture', edit_dispensed_lecture_path(@dispensed_lecture), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this dispensed_lecture', dispensed_lecture_path(@dispensed_lecture), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to dispensed_lectures', dispensed_lectures_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>